version: '3.1'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: grpc-api-user
      POSTGRES_USER: user
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  db-auth:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: grpc-api-auth
      POSTGRES_USER: user
    volumes:
      - ./postgres-data-auth:/var/lib/postgresql/data
    ports:
      - 5433:5433
