version: '3.1'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: grpc-api-product
      POSTGRES_USER: user
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5434:5432
